---
- name: MISP Installation Script for Docker
  hosts: all
  become: yes
  become_method: sudo
  gather_facts: False

  vars_files:
    - "/srv/misp-dockerized/config/misp.conf.yml"  

  pre_tasks:
  - name: read MISP Tag
    shell: "cat /srv/misp-dockerized/docker-compose.yml |grep dcso/misp-server*|cut -d : -f 3|cut -d ' ' -f 1"
    register: MISP
    tags: always

  roles:
   - role: server
     tags: ['server']
   - role: database
     tags: ['database']
     MISP_TAG: "{{ MISP.stdout }}"
   - role: proxy
     tags: ['proxy']