build 1.2-ubuntu:
  extends: .build
  variables:
    VERSION: "1.2-ubuntu"
    TAGS: "${VERSION}-dev 1.0.2-ubuntu"
    RELEASE_DATE: 2018-06


test 1.2-ubuntu:
  extends: .test
  variables:
    VERSION: "1.2-ubuntu"
  only:
    changes:
    - 1.2-ubuntu/*