image: docker:latest

services:
  - docker:dind

stages:
- test
- build

variables:
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_TOKEN
  # DOCKER_SLUG
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # CUSTOM_REGISTRY_URL
  # CUSTOM_REGISTRY_USER
  # CUSTOM_REGISTRY_PW
  DOCKER_DRIVER: overlay2

before_script:
- .ci/01_before_install.sh

.test:
  stage: test
  except: 
  - master  
  script:
  - make build v=$VERSION # build an dcso/CONTAINERNAME image

.build:
  stage: build
  only: 
  - master  
  script:
  - make build v=$VERSION   # build an dcso/CONTAINERNAME image
  - make tags REPO=$CUSTOM_REGISTRY_URL # tagged dcso/CONTAINERNAME + custom-URL/CONTAINERNAME
  - make push REPO=$CUSTOM_REGISTRY_URL USER=$CUSTOM_REGISTRY_USER PW=$CUSTOM_REGISTRY_PW
  - make push REPO=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
  #- make notify-hub-docker-com TOKEN=$DOCKER_HUB_TOKEN


include:
  - '.legacy/.gitlab-ci.yml'
  - '1.0-ubuntu/.gitlab-ci.yml'
  - '1.1-ubuntu/.gitlab-ci.yml'
  - '1.2-ubuntu/.gitlab-ci.yml'
  - '1.3-ubuntu/.gitlab-ci.yml'
  - '2.0-debian/.gitlab-ci.yml'
  - '2.1-debian/.gitlab-ci.yml'
  - '2.2-debian/.gitlab-ci.yml'
  - '2.3-debian/.gitlab-ci.yml'
