image: docker:latest

services:
  - docker:dind

stages:
- test
- build

variables:
  # The following variables are setup via gitlab project group:
  # DOCKER_HUB_NOTIFY_URL
  # DOCKER_SLUG
  # DOCKER_USERNAME
  # DOCKER_PASSWORD
  # CUSTOM_REGISTRY_URL
  # CUSTOM_REGISTRY_USER
  # CUSTOM_REGISTRY_PW

before_script:
- .ci/01_before_install.sh

.test:
  stage: test
  except: 
  - master  
  script:
  - make -C .ci build v=$VERSION

.build:
  stage: build
  only: 
  - master
  - feat/MDD-188
  script:
  - make -C .ci build v=$VERSION 
  - make -C .ci tags REPO=$CUSTOM_REGISTRY_URL
  - make -C .ci tags REPO=$DOCKER_SLUG
  - make -C .ci push REPO=$CUSTOM_REGISTRY_URL USER=$CUSTOM_REGISTRY_USER PW=$CUSTOM_REGISTRY_PW
  - make -C .ci push REPO=$DOCKER_SLUG USER=$DOCKER_USERNAME PW=$DOCKER_PASSWORD
  - make -C .ci notify-hub-docker-com URL=$DOCKER_HUB_NOTIFY_URL


#
# For a cleaner Gitlab CI file include all subfolder which should be build:
#
include:
  - '.legacy/.gitlab-ci.yml'
  - '1.0-ubuntu/.gitlab-ci.yml'
  - '1.1-ubuntu/.gitlab-ci.yml'
  - '1.2-ubuntu/.gitlab-ci.yml'
  - '1.3-ubuntu/.gitlab-ci.yml'
  - '2.0-debian/.gitlab-ci.yml'
  - '2.1-debian/.gitlab-ci.yml'
  - '2.2-debian/.gitlab-ci.yml'
  - '2.3-debian/.gitlab-ci.yml'
  - '2.4-debian/.gitlab-ci.yml'
