

notify:
  extends: .notify

variables:
  COMPONENT: robot

include:
  - project: 'MISP/helper-containers'
    ref: master
    file: '/.gitlab-ci-template.yml'
#
# For a cleaner Gitlab CI file include all subfolder which should be build:
#
  - '1.0-ubuntu/.gitlab-ci.yml'
  - '1.1-ubuntu/.gitlab-ci.yml'
  - '1.2-ubuntu/.gitlab-ci.yml'
  - '1.3-ubuntu/.gitlab-ci.yml'
  - '2.0-debian/.gitlab-ci.yml'
  - '2.1-debian/.gitlab-ci.yml'
  - '2.2-debian/.gitlab-ci.yml'
  - '2.3-debian/.gitlab-ci.yml'
  - '2.4-debian/.gitlab-ci.yml'
