sudo: required
services: docker

env:
  global:
  # Docker Username
  - secure: "iFIZ02XsPHv49u0hNtUfplsI9h3GZ0H8NeM5IR9A20HQ7OINNnuiiYGUVDwwUpLNGzYdUpJTTzFLMV0khOo4MDSfgoOyGvSYf8ojbCod1mdAdzNLcfrlbA62oexpuhkTZIf7rCISAyso4mc0qJ5r60IZNdvRhioIIiHlD/w/sHqXqIkOVK81AGQBuqQNqLLIPz0b5scmhdQIT6eDeswB9yKCRIOMLH1GgNch/e3Ft9pA152gtLiMnhL7SA3ITwM6y4sNHQAUdXB0iwcEQkaHJRqOhxyQRsSX+V9XZ71aLXLt7vPksbOuNuoT2TKFwqljJ2hC4ZtESYw5gep6++Fr/1BZCoxUiuBG4+h1V36bWVIARqpo7wZhsQCkuwh23LP+AzLOLAKTYDsR2JhrWLySn+/lNaPCNPDbsSA+kJGAsU0Gz5fss5blpqgRxFUHBJf6kA++D7fOA2n/dOtSwVBYeOA1ZuQeSWQ9sLqkAnbSa2gBRIdfaDbxEg8eZoSRlXmCF+L5jU5/WjvVmmaeaRYfpYITx0ctIXiflqsfdnjXU2QxMm1gvYhepb0A0ZKh55RhW+sv47RWjNSc7wdwIfTQB5xQDz1IM4/ijcAcxTN8ZSPapy3EK5vcgJPCIEo53m+LzFCMbAYPcSSIoYBsCwsSCLbZVj4X4YJndjOT/C84TP4="
  # Docker Password
  - secure: "dp1+oiM+n892ezSxnEhjA6PCOt7CKeQeuh4Ir6+n8DLRv/udzCOhvvi3qK1tjZ8Fb77MeRtjWYsg+iCjg8d1S3BRMWfUlVRLcTAfCTsMaOzXKwcrVcOcvVuAsr57kS+DCePjQmwd/urXHBkDAzwzuMJHBMEgW5ZUZCONj2T4+SOKC2lTAC7UAH/qYfyTNzUmU7DZgq5ucs4UcK1YYNGEayMNAn+9J8u+7wGk8XuXI249REvW77mCipGJtaAgvHFG0LaHg8qQV6UBKABFaRnTR+pnYxlAKWZ0TCmy+8gnsW5l5u+ABU8jaqU62TbIc3bLwi9syuQWLnOE0E99mK2abT4ZgfsLkqNMpXhD5NpX8ujmjY1SPUq0EM358A6RUqf7qrB3eKgjgtMtiZQq8i34fw0x+g7lCRNN4z3G+d23YfdLavUr9w7SwMgXS9Gtj9pHpIKSZ9L41zrW60KKCcPocEUYAH/cQHTawkMtSeLl1+ZfjvGyoOGd0yLxgQDm+ay56iO6tyZ9K+UARcIZeaEA2ktXFx5bZW+XU6KTRsAOXNy1Sd5okws/bCTK7369eNaG+6TQipL7DWIpjZHtCwPqMA9MezHi07x09BJOevf9Du2tsq05Z1kgb/88dOc3abgpxjHemBlhYuM3b40lUNkJALwSfssY2ctbw0tiZCOjlWg="
  matrix:
  - VERSION=1.0.0 BASE=ubuntu


before_install: 
- './.travis/main.sh'

script:
- travis_retry make build-travis v=${VERSION} b=${BASE}
- travis_retry make tags-travis v=${VERSION} b=${BASE}

after_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# check if branch=master and the current build is no pull request, then push it to docker hub
- if [[ "$TRAVIS_BRANCH" == "master" ]]; then 
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
      make push-image LOCATION=public; 
    fi; 
  fi
# check if branch=develop and the current build is no pull request, then push it to docker hub
- if [[ "$TRAVIS_BRANCH" == "develop" ]]; then 
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then 
      make push-image LOCATION=private; 
    fi; 
  fi

# don't notify me when things fail
notifications:
  email: false