language: minimal
dist: xenial
addons:
  apt:
    sources:
      - docker-xenial

env:
  global:
  #- DOCKER_COMPOSE_VERSION=1.4.2
  - COMPONENT=robot

  matrix:
  # legacy
  - FOLDER=1.0.0-ubuntu
  - FOLDER=1.0.1-ubuntu
  - FOLDER=1.0.2-ubuntu
  - FOLDER=1.0.3-ubuntu
  - FOLDER=1.0.4-debian
  ######################### 
  - FOLDER=1.0-ubuntu
  - FOLDER=1.1-ubuntu
  - FOLDER=1.2-ubuntu
  - FOLDER=1.3-ubuntu
  - FOLDER=2.0-debian
  - FOLDER=2.1-debian
  - FOLDER=2.2-debian
  - FOLDER=2.3-debian
  - FOLDER=2.4-debian

script:
- docker build -f "$TRAVIS_BUILD_DIR/$FOLDER/Dockerfile" 
                      --build-arg VCS_REF="$TRAVIS_COMMIT" 
                      --build-arg VERSION="$FOLDER" 
                      --build-arg GIT_REPO="https://github.com/$TRAVIS_REPO_SLUG" 
                      --build-arg COMPONENT="$COMPONENT"
                      --build-arg BUILD_DATE="$(date -u +"%Y-%m-%d")"
                      "$TRAVIS_BUILD_DIR/$FOLDER"


# don't notify me when things fail
notifications:
  email: false
