#!/bin/bash
sudo: required
services: docker

addons:
  apt:
    packages:
      - docker-ce

env:
 global:
    - CONTAINER=robot
    - LATEST_VERSION=1.0.0
    - LATEST_BASE=ubuntu
  matrix:
    - VERSION=1.0.0 BASE=ubuntu


before_install:
  - git config --global user.name "MISP-dockerized-bot"

install:
  - git clone --recurse-submodules https://github.com/8ear/MISP-dockerized-documentation.git ~/misp-docs

script:
  - travis_retry ./build.sh ${VERSION}-${BASE}
  - ~/misp-docs/official-images/test/run.sh "dcso/misp-${CONTAINER}:$VERSION-${BASE}"


after_sucess:
  - docker tag dcso/misp-${CONTAINER}:${VERSION}-${BASE}
  - docker tag dcso/misp-${CONTAINER}:${LATEST_VERSION}-${LATEST_BASE} dcso/misp-${CONTAINER}:latest

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: 
    docker push dcso/misp-${CONTAINER}-private:${VERSION}-${BASE}
    docker push dcso/misp-${CONTAINER}-private:latest
  on:
    branch: develop


# vim:set et ts=2 sw=2: