test 2.4-debian:
  extends: .test
  variables:
    VERSION: "2.4-debian"
  only:
    changes:
    - 2.4-debian/*

build 2.4-debian:
  extends: .build
  variables:
    VERSION: "2.4-debian"
    TAGS: "${VERSION}-dev latest-dev 2-dev"
