build 1.0-ubuntu:
  extends: .build
  variables:
    VERSION: "1.0-ubuntu"
    TAGS: "${VERSION}-dev"
    RELEASE_DATE: 2018-06


test 1.0-ubuntu:
  extends: .test
  variables:
    VERSION: "1.0-ubuntu"
  only:
    changes:
    - 1.0-ubuntu/*