build 1.3-ubuntu:
  extends: .build
  variables:
    VERSION: "1.3-ubuntu"
    TAGS: "${VERSION}-dev 1.0.3-ubuntu-dev"
    RELEASE_DATE: 2018-09


test 1.3-ubuntu:
  extends: .test
  variables:
    VERSION: "1.3-ubuntu"
  only:
    changes:
    - 1.3-ubuntu/*