build 2.1-debian:
  extends: .build
  variables:
    VERSION: "2.1-debian"
    TAGS: "${VERSION}-dev"
    RELEASE_DATE: 2018-10

test 2.1-debian:
  extends: .test
  variables:
    VERSION: "2.1-debian"
  only:
    changes:
    - 2.1-debian/*