##### Configure SSL #####
- include: tasks/ssl.yml

##### Configure NGINX #####
- name: Proxy | check if HTTP config files exists
  stat: 
    path: "{{SSL_CONFIG_PATH}}/{{HTTP_CONFIG_NAME}}.conf"
  register: server_http

- name: Proxy | check if HTTPS config files exists
  stat: 
    path: "{{SSL_CONFIG_PATH}}/{{HTTPS_CONFIG_NAME}}.conf"
  register: server_https

- name: Proxy | activate https config to proxy
  copy:
    remote_src: True
    src: "{{SERVER_CONFIG_PATH}}/{{ item }}"
    dest: "{{SERVER_CONFIG_PATH}}/{{ item }}.conf"
    force: yes
    owner: root
    group: root
    mode: 0640
  with_items:
    - "{{HTTPS_CONFIG_NAME}}"
  when: server_https.stat.exists is defined and server_https.stat.exists

- name: Proxy | deactivate http config
  shell: "{{ item }}"
  with_items:
    - "mv {{SSL_CONFIG_PATH}}/{{HTTP_CONFIG_NAME}}.conf {{SSL_CONFIG_PATH}}/{{HTTP_CONFIG_NAME}}"
  when: server_http.stat.exists is defined and server_http.stat.exists
    
##### restart Docker Container #####
- name: Proxy | Restart proxy
  # docker_container:
  #   name: misp-proxy
  #   state: started
  #   restart: yes
  shell: docker restart misp-proxy
