##### Configure #####
- name: Proxy | Create SSL directory
  file:
    path: /srv/misp-proxy/ssl
    state: directory
    mode: 0750

- name: Proxy | check if Cert is existing
  local_action: stat path=/srv/misp-dockerized/config/ssl/cert.pem
  register: cert_file

- name: Proxy | check if private Key of Cert is existing
  local_action: stat path=/srv/misp-dockerized/config/ssl/key.pem
  register: cert_key_file

- name: Proxy | No cert found, therefore create internal certificate
  shell: openssl req -x509 -newkey rsa:4096 -keyout /srv/misp-dockerized/config/ssl/key.pem -out /srv/misp-dockerized/config/ssl/cert.pem -days 3650 -nodes -subj '/CN={{MISP_hostname}}'
  when: (cert_file.stat.exists is defined and not cert_file.stat.exists) and (cert_key_file.stat.exists is defined and not cert_key_file.stat.exists)

- name: Proxy | Copy certficate and key to proxy
  become: yes
  copy:
    remote_src: True
    src: "/srv/misp-dockerized/config/ssl/{{ item }}"
    dest: "/srv/misp-proxy/ssl/{{ item }}"
    force: yes
    owner: root
    group: root
    mode: 0750
  with_items:
    - cert.pem
    - key.pem
  when: (cert_file.stat.exists is defined and cert_file.stat.exists) and (cert_key_file.stat.exists is defined and cert_key_file.stat.exists)

- name: Proxy | check if DH params file is existing
  local_action: stat path=/srv/misp-dockerized/config/ssl/dhparams.pem
  register: dh_params

- name: Proxy | copy dh params file to proxy
  become: yes
  copy:
    remote_src: True
    src: "/srv/misp-dockerized/config/ssl/{{ item }}"
    dest: "/srv/misp-proxy/ssl/{{ item }}"
    force: yes
    owner: root
    group: root
    mode: 0750
  with_items:
    - dhparams.pem
  when: (dh_params.stat.exists is defined and dh_params.stat.exists)

- name: Proxy | Create DH params - This can take a long time, so take a break and enjoy a cup of tea or coffee.
  shell: openssl dhparam -out /srv/misp-proxy/ssl/dhparams.pem 2048
  when: dh_params.stat.exists is defined and not dh_params.stat.exists

- name: Proxy | check if HTTP config is activated
  local_action: stat path=/srv/misp-proxy/SERVER_HTTP_only.conf
  register: server_http

- name: Proxy | check if HTTPS config is deactivated
  local_action: stat path=/srv/misp-proxy/SERVER_HTTPS_and_redirected_HTTP
  register: server_https

- name: Proxy | activate https config to proxy
  become: yes
  copy:
    remote_src: True
    src: "/srv/misp-proxy/{{ item }}"
    dest: "/srv/misp-proxy/{{ item }}.conf"
    force: yes
    owner: root
    group: root
    mode: 0750
  with_items:
    - SERVER_HTTPS_and_redirected_HTTP
  when: (server_https.stat.exists is defined and server_https.stat.exists)

- name: Proxy | Switch http to https config 
  become: yes
  shell: "{{ item }}"
  with_items:
    - "mv /srv/misp-proxy/SERVER_HTTP_only.conf /srv/misp-proxy/SERVER_HTTP_only"
    #- "cp /srv/misp-proxy/SERVER_HTTPS_and_redirected_HTTP /srv/misp-proxy/SERVER_HTTPS_and_redirected_HTTP.conf"
  when: (server_http.stat.exists is defined and server_http.stat.exists)
    

# Reload Proxy Config
- name: Proxy | Restart proxy
  become: yes
  shell: "{{ item }}"
  with_items:
    - "docker restart misp-proxy"

